// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

// 
//This source code was auto-generated by MonoXSD
//
namespace Schemas {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:ietf:params:xml:ns:iodef-1.0")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="urn:ietf:params:xml:ns:iodef-1.0")]
    public partial class IncidentID {
        
        private string nameField;
        
        private string instanceField;
        
        private string restrictionField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public string instance {
            get {
                return this.instanceField;
            }
            set {
                this.instanceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public string restriction {
            get {
                return this.restrictionField;
            }
            set {
                this.restrictionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:ietf:params:xml:ns:iodef-1.0")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="urn:ietf:params:xml:ns:iodef-1.0")]
    public partial class Description {
        
        private string langField;
        
        private string valueField1;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public string lang {
            get {
                return this.langField;
            }
            set {
                this.langField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField1;
            }
            set {
                this.valueField1 = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:ietf:params:xml:ns:iodef-1.0")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="urn:ietf:params:xml:ns:iodef-1.0", IsNullable=true)]
    public partial class iodef_sci {
        
        private string langField1;
        
        private string valueField2;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public string lang {
            get {
                return this.langField1;
            }
            set {
                this.langField1 = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField2;
            }
            set {
                this.valueField2 = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:ietf:params:xml:ns:iodef-1.0")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="urn:ietf:params:xml:ns:iodef-1.0")]
    public partial class IODEF_Document {
        
        private string versionField;
        
        private string langField2;
        
        private string formatidField;
        
        private IODEF_DocumentIncident[] incidentField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public string version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public string lang {
            get {
                return this.langField2;
            }
            set {
                this.langField2 = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public string formatid {
            get {
                return this.formatidField;
            }
            set {
                this.formatidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Incident")]
        public IODEF_DocumentIncident[] Incident {
            get {
                return this.incidentField;
            }
            set {
                this.incidentField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:ietf:params:xml:ns:iodef-1.0")]
    public partial class IODEF_DocumentIncident {
        
        private string purposeField;
        
        private string ext_purposeField;
        
        private string langField3;
        
        private string restrictionField1;
        
        private string detectTimeField;
        
        private string startTimeField;
        
        private string endTimeField;
        
        private string reportTimeField;
        
        private IncidentID[] incidentIDField;
        
        private IODEF_DocumentIncidentAlternativeID[] alternativeIDField;
        
        private IODEF_DocumentIncidentRelatedActivity[] relatedActivityField;
        
        private Description[] descriptionField;
        
        private IODEF_DocumentIncidentAssessment[] assessmentField;
        
        private IODEF_DocumentIncidentMethod[] methodField;
        
        private IODEF_DocumentIncidentContact[] contactField;
        
        private IODEF_DocumentIncidentEventData[] eventDataField;
        
        private IODEF_DocumentIncidentHistory[] historyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public string purpose {
            get {
                return this.purposeField;
            }
            set {
                this.purposeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public string ext_purpose {
            get {
                return this.ext_purposeField;
            }
            set {
                this.ext_purposeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public string lang {
            get {
                return this.langField3;
            }
            set {
                this.langField3 = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public string restriction {
            get {
                return this.restrictionField1;
            }
            set {
                this.restrictionField1 = value;
            }
        }
        
        /// <remarks/>
        public string DetectTime {
            get {
                return this.detectTimeField;
            }
            set {
                this.detectTimeField = value;
            }
        }
        
        /// <remarks/>
        public string StartTime {
            get {
                return this.startTimeField;
            }
            set {
                this.startTimeField = value;
            }
        }
        
        /// <remarks/>
        public string EndTime {
            get {
                return this.endTimeField;
            }
            set {
                this.endTimeField = value;
            }
        }
        
        /// <remarks/>
        public string ReportTime {
            get {
                return this.reportTimeField;
            }
            set {
                this.reportTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("IncidentID", IsNullable=true)]
        public IncidentID[] IncidentID {
            get {
                return this.incidentIDField;
            }
            set {
                this.incidentIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("AlternativeID")]
        public IODEF_DocumentIncidentAlternativeID[] AlternativeID {
            get {
                return this.alternativeIDField;
            }
            set {
                this.alternativeIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("RelatedActivity")]
        public IODEF_DocumentIncidentRelatedActivity[] RelatedActivity {
            get {
                return this.relatedActivityField;
            }
            set {
                this.relatedActivityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Description", IsNullable=true)]
        public Description[] Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Assessment")]
        public IODEF_DocumentIncidentAssessment[] Assessment {
            get {
                return this.assessmentField;
            }
            set {
                this.assessmentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Method")]
        public IODEF_DocumentIncidentMethod[] Method {
            get {
                return this.methodField;
            }
            set {
                this.methodField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Contact")]
        public IODEF_DocumentIncidentContact[] Contact {
            get {
                return this.contactField;
            }
            set {
                this.contactField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("EventData")]
        public IODEF_DocumentIncidentEventData[] EventData {
            get {
                return this.eventDataField;
            }
            set {
                this.eventDataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("History")]
        public IODEF_DocumentIncidentHistory[] History {
            get {
                return this.historyField;
            }
            set {
                this.historyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:ietf:params:xml:ns:iodef-1.0")]
    public partial class IODEF_DocumentIncidentAlternativeID {
        
        private string restrictionField2;
        
        private IncidentID[] incidentIDField1;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public string restriction {
            get {
                return this.restrictionField2;
            }
            set {
                this.restrictionField2 = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("IncidentID", IsNullable=true)]
        public IncidentID[] IncidentID {
            get {
                return this.incidentIDField1;
            }
            set {
                this.incidentIDField1 = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:ietf:params:xml:ns:iodef-1.0")]
    public partial class IODEF_DocumentIncidentRelatedActivity {
        
        private string restrictionField3;
        
        private IncidentID[] incidentIDField2;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public string restriction {
            get {
                return this.restrictionField3;
            }
            set {
                this.restrictionField3 = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("IncidentID", IsNullable=true)]
        public IncidentID[] IncidentID {
            get {
                return this.incidentIDField2;
            }
            set {
                this.incidentIDField2 = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:ietf:params:xml:ns:iodef-1.0")]
    public partial class IODEF_DocumentIncidentAssessment {
        
        private string occurrenceField;
        
        private string restrictionField4;
        
        private IODEF_DocumentIncidentAssessmentImpact[] impactField;
        
        private IODEF_DocumentIncidentAssessmentTimeImpact[] timeImpactField;
        
        private IODEF_DocumentIncidentAssessmentMonetaryImpact[] monetaryImpactField;
        
        private IODEF_DocumentIncidentAssessmentCounter[] counterField;
        
        private IODEF_DocumentIncidentAssessmentConfidence[] confidenceField;
        
        private IODEF_DocumentIncidentAssessmentAdditionalData[] additionalDataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public string occurrence {
            get {
                return this.occurrenceField;
            }
            set {
                this.occurrenceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public string restriction {
            get {
                return this.restrictionField4;
            }
            set {
                this.restrictionField4 = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Impact", IsNullable=true)]
        public IODEF_DocumentIncidentAssessmentImpact[] Impact {
            get {
                return this.impactField;
            }
            set {
                this.impactField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("TimeImpact", IsNullable=true)]
        public IODEF_DocumentIncidentAssessmentTimeImpact[] TimeImpact {
            get {
                return this.timeImpactField;
            }
            set {
                this.timeImpactField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("MonetaryImpact", IsNullable=true)]
        public IODEF_DocumentIncidentAssessmentMonetaryImpact[] MonetaryImpact {
            get {
                return this.monetaryImpactField;
            }
            set {
                this.monetaryImpactField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Counter", IsNullable=true)]
        public IODEF_DocumentIncidentAssessmentCounter[] Counter {
            get {
                return this.counterField;
            }
            set {
                this.counterField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Confidence", IsNullable=true)]
        public IODEF_DocumentIncidentAssessmentConfidence[] Confidence {
            get {
                return this.confidenceField;
            }
            set {
                this.confidenceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("AdditionalData", IsNullable=true)]
        public IODEF_DocumentIncidentAssessmentAdditionalData[] AdditionalData {
            get {
                return this.additionalDataField;
            }
            set {
                this.additionalDataField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:ietf:params:xml:ns:iodef-1.0")]
    public partial class IODEF_DocumentIncidentAssessmentImpact {
        
        private string severityField;
        
        private string completionField;
        
        private string typeField;
        
        private string ext_typeField;
        
        private string langField4;
        
        private string valueField3;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public string severity {
            get {
                return this.severityField;
            }
            set {
                this.severityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public string completion {
            get {
                return this.completionField;
            }
            set {
                this.completionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public string ext_type {
            get {
                return this.ext_typeField;
            }
            set {
                this.ext_typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public string lang {
            get {
                return this.langField4;
            }
            set {
                this.langField4 = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField3;
            }
            set {
                this.valueField3 = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:ietf:params:xml:ns:iodef-1.0")]
    public partial class IODEF_DocumentIncidentAssessmentTimeImpact {
        
        private string severityField1;
        
        private string metricField;
        
        private string ext_metricField;
        
        private string durationField;
        
        private string ext_durationField;
        
        private string valueField4;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public string severity {
            get {
                return this.severityField1;
            }
            set {
                this.severityField1 = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public string metric {
            get {
                return this.metricField;
            }
            set {
                this.metricField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public string ext_metric {
            get {
                return this.ext_metricField;
            }
            set {
                this.ext_metricField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public string duration {
            get {
                return this.durationField;
            }
            set {
                this.durationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public string ext_duration {
            get {
                return this.ext_durationField;
            }
            set {
                this.ext_durationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField4;
            }
            set {
                this.valueField4 = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:ietf:params:xml:ns:iodef-1.0")]
    public partial class IODEF_DocumentIncidentAssessmentMonetaryImpact {
        
        private string severityField2;
        
        private string currencyField;
        
        private string valueField5;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public string severity {
            get {
                return this.severityField2;
            }
            set {
                this.severityField2 = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public string currency {
            get {
                return this.currencyField;
            }
            set {
                this.currencyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField5;
            }
            set {
                this.valueField5 = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:ietf:params:xml:ns:iodef-1.0")]
    public partial class IODEF_DocumentIncidentAssessmentCounter {
        
        private string typeField1;
        
        private string ext_typeField1;
        
        private string meaningField;
        
        private string durationField1;
        
        private string ext_durationField1;
        
        private string valueField6;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public string type {
            get {
                return this.typeField1;
            }
            set {
                this.typeField1 = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public string ext_type {
            get {
                return this.ext_typeField1;
            }
            set {
                this.ext_typeField1 = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public string meaning {
            get {
                return this.meaningField;
            }
            set {
                this.meaningField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public string duration {
            get {
                return this.durationField1;
            }
            set {
                this.durationField1 = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public string ext_duration {
            get {
                return this.ext_durationField1;
            }
            set {
                this.ext_durationField1 = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField6;
            }
            set {
                this.valueField6 = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:ietf:params:xml:ns:iodef-1.0")]
    public partial class IODEF_DocumentIncidentAssessmentConfidence {
        
        private string ratingField;
        
        private string valueField7;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public string rating {
            get {
                return this.ratingField;
            }
            set {
                this.ratingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField7;
            }
            set {
                this.valueField7 = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:ietf:params:xml:ns:iodef-1.0")]
    public partial class IODEF_DocumentIncidentAssessmentAdditionalData {
        
        private string dtypeField;
        
        private string ext_dtypeField;
        
        private string meaningField1;
        
        private string formatidField1;
        
        private string restrictionField5;
        
        private string valueField8;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public string dtype {
            get {
                return this.dtypeField;
            }
            set {
                this.dtypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public string ext_dtype {
            get {
                return this.ext_dtypeField;
            }
            set {
                this.ext_dtypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public string meaning {
            get {
                return this.meaningField1;
            }
            set {
                this.meaningField1 = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public string formatid {
            get {
                return this.formatidField1;
            }
            set {
                this.formatidField1 = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public string restriction {
            get {
                return this.restrictionField5;
            }
            set {
                this.restrictionField5 = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField8;
            }
            set {
                this.valueField8 = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:ietf:params:xml:ns:iodef-1.0")]
    public partial class IODEF_DocumentIncidentMethod {
        
        private string restrictionField6;
        
        private IODEF_DocumentIncidentMethodReference[] referenceField;
        
        private Description[] descriptionField1;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public string restriction {
            get {
                return this.restrictionField6;
            }
            set {
                this.restrictionField6 = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Reference")]
        public IODEF_DocumentIncidentMethodReference[] Reference {
            get {
                return this.referenceField;
            }
            set {
                this.referenceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Description", IsNullable=true)]
        public Description[] Description {
            get {
                return this.descriptionField1;
            }
            set {
                this.descriptionField1 = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:ietf:params:xml:ns:iodef-1.0")]
    public partial class IODEF_DocumentIncidentMethodReference {
        
        private IODEF_DocumentIncidentMethodReferenceReferenceName[] referenceNameField;
        
        private IODEF_DocumentIncidentMethodReferenceURL[] uRLField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ReferenceName", IsNullable=true)]
        public IODEF_DocumentIncidentMethodReferenceReferenceName[] ReferenceName {
            get {
                return this.referenceNameField;
            }
            set {
                this.referenceNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("URL", IsNullable=true)]
        public IODEF_DocumentIncidentMethodReferenceURL[] URL {
            get {
                return this.uRLField;
            }
            set {
                this.uRLField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:ietf:params:xml:ns:iodef-1.0")]
    public partial class IODEF_DocumentIncidentMethodReferenceReferenceName {
        
        private string langField5;
        
        private string valueField9;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public string lang {
            get {
                return this.langField5;
            }
            set {
                this.langField5 = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField9;
            }
            set {
                this.valueField9 = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:ietf:params:xml:ns:iodef-1.0")]
    public partial class IODEF_DocumentIncidentMethodReferenceURL {
        
        private string valueField10;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField10;
            }
            set {
                this.valueField10 = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:ietf:params:xml:ns:iodef-1.0")]
    public partial class IODEF_DocumentIncidentContact {
        
        private string roleField;
        
        private string ext_roleField;
        
        private string typeField2;
        
        private string ext_typeField2;
        
        private string restrictionField7;
        
        private string timezoneField;
        
        private IODEF_DocumentIncidentContactContactName[] contactNameField;
        
        private IODEF_DocumentIncidentContactRegistryHandle[] registryHandleField;
        
        private IODEF_DocumentIncidentContactPostalAddress[] postalAddressField;
        
        private IODEF_DocumentIncidentContactEmail[] emailField;
        
        private IODEF_DocumentIncidentContactTelephone[] telephoneField;
        
        private IODEF_DocumentIncidentContactFax[] faxField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public string role {
            get {
                return this.roleField;
            }
            set {
                this.roleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public string ext_role {
            get {
                return this.ext_roleField;
            }
            set {
                this.ext_roleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public string type {
            get {
                return this.typeField2;
            }
            set {
                this.typeField2 = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public string ext_type {
            get {
                return this.ext_typeField2;
            }
            set {
                this.ext_typeField2 = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public string restriction {
            get {
                return this.restrictionField7;
            }
            set {
                this.restrictionField7 = value;
            }
        }
        
        /// <remarks/>
        public string Timezone {
            get {
                return this.timezoneField;
            }
            set {
                this.timezoneField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ContactName", IsNullable=true)]
        public IODEF_DocumentIncidentContactContactName[] ContactName {
            get {
                return this.contactNameField;
            }
            set {
                this.contactNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("RegistryHandle", IsNullable=true)]
        public IODEF_DocumentIncidentContactRegistryHandle[] RegistryHandle {
            get {
                return this.registryHandleField;
            }
            set {
                this.registryHandleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PostalAddress", IsNullable=true)]
        public IODEF_DocumentIncidentContactPostalAddress[] PostalAddress {
            get {
                return this.postalAddressField;
            }
            set {
                this.postalAddressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Email", IsNullable=true)]
        public IODEF_DocumentIncidentContactEmail[] Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Telephone", IsNullable=true)]
        public IODEF_DocumentIncidentContactTelephone[] Telephone {
            get {
                return this.telephoneField;
            }
            set {
                this.telephoneField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Fax", IsNullable=true)]
        public IODEF_DocumentIncidentContactFax[] Fax {
            get {
                return this.faxField;
            }
            set {
                this.faxField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:ietf:params:xml:ns:iodef-1.0")]
    public partial class IODEF_DocumentIncidentContactContactName {
        
        private string langField6;
        
        private string valueField11;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public string lang {
            get {
                return this.langField6;
            }
            set {
                this.langField6 = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField11;
            }
            set {
                this.valueField11 = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:ietf:params:xml:ns:iodef-1.0")]
    public partial class IODEF_DocumentIncidentContactRegistryHandle {
        
        private string registryField;
        
        private string ext_registryField;
        
        private string valueField12;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public string registry {
            get {
                return this.registryField;
            }
            set {
                this.registryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public string ext_registry {
            get {
                return this.ext_registryField;
            }
            set {
                this.ext_registryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField12;
            }
            set {
                this.valueField12 = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:ietf:params:xml:ns:iodef-1.0")]
    public partial class IODEF_DocumentIncidentContactPostalAddress {
        
        private string meaningField2;
        
        private string langField7;
        
        private string valueField13;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public string meaning {
            get {
                return this.meaningField2;
            }
            set {
                this.meaningField2 = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public string lang {
            get {
                return this.langField7;
            }
            set {
                this.langField7 = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField13;
            }
            set {
                this.valueField13 = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:ietf:params:xml:ns:iodef-1.0")]
    public partial class IODEF_DocumentIncidentContactEmail {
        
        private string meaningField3;
        
        private string valueField14;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public string meaning {
            get {
                return this.meaningField3;
            }
            set {
                this.meaningField3 = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField14;
            }
            set {
                this.valueField14 = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:ietf:params:xml:ns:iodef-1.0")]
    public partial class IODEF_DocumentIncidentContactTelephone {
        
        private string meaningField4;
        
        private string valueField15;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public string meaning {
            get {
                return this.meaningField4;
            }
            set {
                this.meaningField4 = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField15;
            }
            set {
                this.valueField15 = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:ietf:params:xml:ns:iodef-1.0")]
    public partial class IODEF_DocumentIncidentContactFax {
        
        private string meaningField5;
        
        private string valueField16;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public string meaning {
            get {
                return this.meaningField5;
            }
            set {
                this.meaningField5 = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField16;
            }
            set {
                this.valueField16 = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:ietf:params:xml:ns:iodef-1.0")]
    public partial class IODEF_DocumentIncidentEventData {
        
        private string restrictionField8;
        
        private string detectTimeField1;
        
        private string startTimeField1;
        
        private string endTimeField1;
        
        private IODEF_DocumentIncidentEventDataFlowSystem[][] flowField;
        
        private IODEF_DocumentIncidentEventDataExpectation[] expectationField;
        
        private IODEF_DocumentIncidentEventDataRecord[] recordField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public string restriction {
            get {
                return this.restrictionField8;
            }
            set {
                this.restrictionField8 = value;
            }
        }
        
        /// <remarks/>
        public string DetectTime {
            get {
                return this.detectTimeField1;
            }
            set {
                this.detectTimeField1 = value;
            }
        }
        
        /// <remarks/>
        public string StartTime {
            get {
                return this.startTimeField1;
            }
            set {
                this.startTimeField1 = value;
            }
        }
        
        /// <remarks/>
        public string EndTime {
            get {
                return this.endTimeField1;
            }
            set {
                this.endTimeField1 = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Flow")]
        public IODEF_DocumentIncidentEventDataFlowSystem[][] Flow {
            get {
                return this.flowField;
            }
            set {
                this.flowField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Expectation")]
        public IODEF_DocumentIncidentEventDataExpectation[] Expectation {
            get {
                return this.expectationField;
            }
            set {
                this.expectationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Record")]
        public IODEF_DocumentIncidentEventDataRecord[] Record {
            get {
                return this.recordField;
            }
            set {
                this.recordField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:ietf:params:xml:ns:iodef-1.0")]
    public partial class IODEF_DocumentIncidentEventDataFlowSystem {
        
        private string restrictionField9;
        
        private string interfaceField;
        
        private string categoryField;
        
        private string ext_categoryField;
        
        private string spoofedField;
        
        private IODEF_DocumentIncidentEventDataFlowSystemNode[] nodeField;
        
        private IODEF_DocumentIncidentEventDataFlowSystemService[] serviceField;
        
        private IODEF_DocumentIncidentEventDataFlowSystemOperatingSystem[] operatingSystemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public string restriction {
            get {
                return this.restrictionField9;
            }
            set {
                this.restrictionField9 = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public string @interface {
            get {
                return this.interfaceField;
            }
            set {
                this.interfaceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public string category {
            get {
                return this.categoryField;
            }
            set {
                this.categoryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public string ext_category {
            get {
                return this.ext_categoryField;
            }
            set {
                this.ext_categoryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public string spoofed {
            get {
                return this.spoofedField;
            }
            set {
                this.spoofedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Node")]
        public IODEF_DocumentIncidentEventDataFlowSystemNode[] Node {
            get {
                return this.nodeField;
            }
            set {
                this.nodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Service")]
        public IODEF_DocumentIncidentEventDataFlowSystemService[] Service {
            get {
                return this.serviceField;
            }
            set {
                this.serviceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("OperatingSystem")]
        public IODEF_DocumentIncidentEventDataFlowSystemOperatingSystem[] OperatingSystem {
            get {
                return this.operatingSystemField;
            }
            set {
                this.operatingSystemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:ietf:params:xml:ns:iodef-1.0")]
    public partial class IODEF_DocumentIncidentEventDataFlowSystemNode {
        
        private string counterField1;
        
        private string dateTimeField;
        
        private IODEF_DocumentIncidentEventDataFlowSystemNodeNodeName[] nodeNameField;
        
        private IODEF_DocumentIncidentEventDataFlowSystemNodeAddress[] addressField;
        
        private IODEF_DocumentIncidentEventDataFlowSystemNodeLocation[] locationField;
        
        private IODEF_DocumentIncidentEventDataFlowSystemNodeNodeRole[] nodeRoleField;
        
        /// <remarks/>
        public string Counter {
            get {
                return this.counterField1;
            }
            set {
                this.counterField1 = value;
            }
        }
        
        /// <remarks/>
        public string DateTime {
            get {
                return this.dateTimeField;
            }
            set {
                this.dateTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("NodeName", IsNullable=true)]
        public IODEF_DocumentIncidentEventDataFlowSystemNodeNodeName[] NodeName {
            get {
                return this.nodeNameField;
            }
            set {
                this.nodeNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Address", IsNullable=true)]
        public IODEF_DocumentIncidentEventDataFlowSystemNodeAddress[] Address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Location", IsNullable=true)]
        public IODEF_DocumentIncidentEventDataFlowSystemNodeLocation[] Location {
            get {
                return this.locationField;
            }
            set {
                this.locationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("NodeRole", IsNullable=true)]
        public IODEF_DocumentIncidentEventDataFlowSystemNodeNodeRole[] NodeRole {
            get {
                return this.nodeRoleField;
            }
            set {
                this.nodeRoleField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:ietf:params:xml:ns:iodef-1.0")]
    public partial class IODEF_DocumentIncidentEventDataFlowSystemNodeNodeName {
        
        private string langField8;
        
        private string valueField17;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public string lang {
            get {
                return this.langField8;
            }
            set {
                this.langField8 = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField17;
            }
            set {
                this.valueField17 = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:ietf:params:xml:ns:iodef-1.0")]
    public partial class IODEF_DocumentIncidentEventDataFlowSystemNodeAddress {
        
        private string categoryField1;
        
        private string ext_categoryField1;
        
        private string vlan_nameField;
        
        private string vlan_numField;
        
        private string valueField18;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public string category {
            get {
                return this.categoryField1;
            }
            set {
                this.categoryField1 = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public string ext_category {
            get {
                return this.ext_categoryField1;
            }
            set {
                this.ext_categoryField1 = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public string vlan_name {
            get {
                return this.vlan_nameField;
            }
            set {
                this.vlan_nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public string vlan_num {
            get {
                return this.vlan_numField;
            }
            set {
                this.vlan_numField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField18;
            }
            set {
                this.valueField18 = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:ietf:params:xml:ns:iodef-1.0")]
    public partial class IODEF_DocumentIncidentEventDataFlowSystemNodeLocation {
        
        private string langField9;
        
        private string valueField19;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public string lang {
            get {
                return this.langField9;
            }
            set {
                this.langField9 = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField19;
            }
            set {
                this.valueField19 = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:ietf:params:xml:ns:iodef-1.0")]
    public partial class IODEF_DocumentIncidentEventDataFlowSystemNodeNodeRole {
        
        private string categoryField2;
        
        private string ext_categoryField2;
        
        private string langField10;
        
        private string valueField20;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public string category {
            get {
                return this.categoryField2;
            }
            set {
                this.categoryField2 = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public string ext_category {
            get {
                return this.ext_categoryField2;
            }
            set {
                this.ext_categoryField2 = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public string lang {
            get {
                return this.langField10;
            }
            set {
                this.langField10 = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField20;
            }
            set {
                this.valueField20 = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:ietf:params:xml:ns:iodef-1.0")]
    public partial class IODEF_DocumentIncidentEventDataFlowSystemService {
        
        private string ip_protocolField;
        
        private string portField;
        
        private string portlistField;
        
        private string protoTypeField;
        
        private string protoCodeField;
        
        private string protoFieldField;
        
        private IODEF_DocumentIncidentEventDataFlowSystemServiceApplication[] applicationField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public string ip_protocol {
            get {
                return this.ip_protocolField;
            }
            set {
                this.ip_protocolField = value;
            }
        }
        
        /// <remarks/>
        public string Port {
            get {
                return this.portField;
            }
            set {
                this.portField = value;
            }
        }
        
        /// <remarks/>
        public string Portlist {
            get {
                return this.portlistField;
            }
            set {
                this.portlistField = value;
            }
        }
        
        /// <remarks/>
        public string ProtoType {
            get {
                return this.protoTypeField;
            }
            set {
                this.protoTypeField = value;
            }
        }
        
        /// <remarks/>
        public string ProtoCode {
            get {
                return this.protoCodeField;
            }
            set {
                this.protoCodeField = value;
            }
        }
        
        /// <remarks/>
        public string ProtoField {
            get {
                return this.protoFieldField;
            }
            set {
                this.protoFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Application")]
        public IODEF_DocumentIncidentEventDataFlowSystemServiceApplication[] Application {
            get {
                return this.applicationField;
            }
            set {
                this.applicationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:ietf:params:xml:ns:iodef-1.0")]
    public partial class IODEF_DocumentIncidentEventDataFlowSystemServiceApplication {
        
        private string swidField;
        
        private string configidField;
        
        private string vendorField;
        
        private string familyField;
        
        private string nameField1;
        
        private string versionField1;
        
        private string patchField;
        
        private string uRLField1;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public string swid {
            get {
                return this.swidField;
            }
            set {
                this.swidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public string configid {
            get {
                return this.configidField;
            }
            set {
                this.configidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public string vendor {
            get {
                return this.vendorField;
            }
            set {
                this.vendorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public string family {
            get {
                return this.familyField;
            }
            set {
                this.familyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public string name {
            get {
                return this.nameField1;
            }
            set {
                this.nameField1 = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public string version {
            get {
                return this.versionField1;
            }
            set {
                this.versionField1 = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public string patch {
            get {
                return this.patchField;
            }
            set {
                this.patchField = value;
            }
        }
        
        /// <remarks/>
        public string URL {
            get {
                return this.uRLField1;
            }
            set {
                this.uRLField1 = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:ietf:params:xml:ns:iodef-1.0")]
    public partial class IODEF_DocumentIncidentEventDataFlowSystemOperatingSystem {
        
        private string swidField1;
        
        private string configidField1;
        
        private string vendorField1;
        
        private string familyField1;
        
        private string nameField2;
        
        private string versionField2;
        
        private string patchField1;
        
        private string uRLField2;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public string swid {
            get {
                return this.swidField1;
            }
            set {
                this.swidField1 = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public string configid {
            get {
                return this.configidField1;
            }
            set {
                this.configidField1 = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public string vendor {
            get {
                return this.vendorField1;
            }
            set {
                this.vendorField1 = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public string family {
            get {
                return this.familyField1;
            }
            set {
                this.familyField1 = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public string name {
            get {
                return this.nameField2;
            }
            set {
                this.nameField2 = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public string version {
            get {
                return this.versionField2;
            }
            set {
                this.versionField2 = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public string patch {
            get {
                return this.patchField1;
            }
            set {
                this.patchField1 = value;
            }
        }
        
        /// <remarks/>
        public string URL {
            get {
                return this.uRLField2;
            }
            set {
                this.uRLField2 = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:ietf:params:xml:ns:iodef-1.0")]
    public partial class IODEF_DocumentIncidentEventDataExpectation {
        
        private string restrictionField10;
        
        private string severityField3;
        
        private string actionField;
        
        private string ext_actionField;
        
        private string startTimeField2;
        
        private string endTimeField2;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public string restriction {
            get {
                return this.restrictionField10;
            }
            set {
                this.restrictionField10 = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public string severity {
            get {
                return this.severityField3;
            }
            set {
                this.severityField3 = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public string action {
            get {
                return this.actionField;
            }
            set {
                this.actionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public string ext_action {
            get {
                return this.ext_actionField;
            }
            set {
                this.ext_actionField = value;
            }
        }
        
        /// <remarks/>
        public string StartTime {
            get {
                return this.startTimeField2;
            }
            set {
                this.startTimeField2 = value;
            }
        }
        
        /// <remarks/>
        public string EndTime {
            get {
                return this.endTimeField2;
            }
            set {
                this.endTimeField2 = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:ietf:params:xml:ns:iodef-1.0")]
    public partial class IODEF_DocumentIncidentEventDataRecord {
        
        private string restrictionField11;
        
        private IODEF_DocumentIncidentEventDataRecordRecordData[] recordDataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public string restriction {
            get {
                return this.restrictionField11;
            }
            set {
                this.restrictionField11 = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("RecordData")]
        public IODEF_DocumentIncidentEventDataRecordRecordData[] RecordData {
            get {
                return this.recordDataField;
            }
            set {
                this.recordDataField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:ietf:params:xml:ns:iodef-1.0")]
    public partial class IODEF_DocumentIncidentEventDataRecordRecordData {
        
        private string restrictionField12;
        
        private string dateTimeField1;
        
        private IODEF_DocumentIncidentEventDataRecordRecordDataRecordPattern[] recordPatternField;
        
        private IODEF_DocumentIncidentEventDataRecordRecordDataRecordItem[] recordItemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public string restriction {
            get {
                return this.restrictionField12;
            }
            set {
                this.restrictionField12 = value;
            }
        }
        
        /// <remarks/>
        public string DateTime {
            get {
                return this.dateTimeField1;
            }
            set {
                this.dateTimeField1 = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("RecordPattern", IsNullable=true)]
        public IODEF_DocumentIncidentEventDataRecordRecordDataRecordPattern[] RecordPattern {
            get {
                return this.recordPatternField;
            }
            set {
                this.recordPatternField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("RecordItem", IsNullable=true)]
        public IODEF_DocumentIncidentEventDataRecordRecordDataRecordItem[] RecordItem {
            get {
                return this.recordItemField;
            }
            set {
                this.recordItemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:ietf:params:xml:ns:iodef-1.0")]
    public partial class IODEF_DocumentIncidentEventDataRecordRecordDataRecordPattern {
        
        private string typeField3;
        
        private string ext_typeField3;
        
        private string offsetField;
        
        private string offsetunitField;
        
        private string ext_offsetunitField;
        
        private string instanceField1;
        
        private string valueField21;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public string type {
            get {
                return this.typeField3;
            }
            set {
                this.typeField3 = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public string ext_type {
            get {
                return this.ext_typeField3;
            }
            set {
                this.ext_typeField3 = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public string offset {
            get {
                return this.offsetField;
            }
            set {
                this.offsetField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public string offsetunit {
            get {
                return this.offsetunitField;
            }
            set {
                this.offsetunitField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public string ext_offsetunit {
            get {
                return this.ext_offsetunitField;
            }
            set {
                this.ext_offsetunitField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public string instance {
            get {
                return this.instanceField1;
            }
            set {
                this.instanceField1 = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField21;
            }
            set {
                this.valueField21 = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:ietf:params:xml:ns:iodef-1.0")]
    public partial class IODEF_DocumentIncidentEventDataRecordRecordDataRecordItem {
        
        private string dtypeField1;
        
        private string ext_dtypeField1;
        
        private string meaningField6;
        
        private string formatidField2;
        
        private string restrictionField13;
        
        private string valueField22;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public string dtype {
            get {
                return this.dtypeField1;
            }
            set {
                this.dtypeField1 = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public string ext_dtype {
            get {
                return this.ext_dtypeField1;
            }
            set {
                this.ext_dtypeField1 = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public string meaning {
            get {
                return this.meaningField6;
            }
            set {
                this.meaningField6 = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public string formatid {
            get {
                return this.formatidField2;
            }
            set {
                this.formatidField2 = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public string restriction {
            get {
                return this.restrictionField13;
            }
            set {
                this.restrictionField13 = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField22;
            }
            set {
                this.valueField22 = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:ietf:params:xml:ns:iodef-1.0")]
    public partial class IODEF_DocumentIncidentHistory {
        
        private string restrictionField14;
        
        private IODEF_DocumentIncidentHistoryHistoryItem[] historyItemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public string restriction {
            get {
                return this.restrictionField14;
            }
            set {
                this.restrictionField14 = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("HistoryItem")]
        public IODEF_DocumentIncidentHistoryHistoryItem[] HistoryItem {
            get {
                return this.historyItemField;
            }
            set {
                this.historyItemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:ietf:params:xml:ns:iodef-1.0")]
    public partial class IODEF_DocumentIncidentHistoryHistoryItem {
        
        private string restrictionField15;
        
        private string actionField1;
        
        private string ext_actionField1;
        
        private string dateTimeField2;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public string restriction {
            get {
                return this.restrictionField15;
            }
            set {
                this.restrictionField15 = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public string action {
            get {
                return this.actionField1;
            }
            set {
                this.actionField1 = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public string ext_action {
            get {
                return this.ext_actionField1;
            }
            set {
                this.ext_actionField1 = value;
            }
        }
        
        /// <remarks/>
        public string DateTime {
            get {
                return this.dateTimeField2;
            }
            set {
                this.dateTimeField2 = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:ietf:params:xml:ns:iodef-1.0")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="urn:ietf:params:xml:ns:iodef-1.0", IsNullable=false)]
    public partial class NewDataSet {
        
        private object[] itemsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("IncidentID", Type=typeof(IncidentID), IsNullable=true)]
        [System.Xml.Serialization.XmlElementAttribute("Description", Type=typeof(Description), IsNullable=true)]
        [System.Xml.Serialization.XmlElementAttribute("IODEF_Document", Type=typeof(IODEF_Document))]
        public object[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
    }
}
