//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.23 at 09:39:40 PM JST 
//


package ietf.params.xml.ns.iodef_2;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for BusinessImpactType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BusinessImpactType"&gt;
 *   &lt;simpleContent&gt;
 *     &lt;extension base="&lt;urn:ietf:params:xml:ns:iodef-2.0&gt;MLStringType"&gt;
 *       &lt;attribute name="severity" type="{urn:ietf:params:xml:ns:iodef-2.0}businessimpact-severity-type" /&gt;
 *       &lt;attribute name="ext-severity" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="type" type="{urn:ietf:params:xml:ns:iodef-2.0}businessimpact-type-type" /&gt;
 *       &lt;attribute name="ext-type" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/extension&gt;
 *   &lt;/simpleContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BusinessImpactType")
public class BusinessImpactType
    extends MLStringType
{

    @XmlAttribute(name = "severity")
    protected BusinessimpactSeverityType severity;
    @XmlAttribute(name = "ext-severity")
    protected String extSeverity;
    @XmlAttribute(name = "type")
    protected BusinessimpactTypeType type;
    @XmlAttribute(name = "ext-type")
    protected String extType;

    /**
     * Gets the value of the severity property.
     * 
     * @return
     *     possible object is
     *     {@link BusinessimpactSeverityType }
     *     
     */
    public BusinessimpactSeverityType getSeverity() {
        return severity;
    }

    /**
     * Sets the value of the severity property.
     * 
     * @param value
     *     allowed object is
     *     {@link BusinessimpactSeverityType }
     *     
     */
    public void setSeverity(BusinessimpactSeverityType value) {
        this.severity = value;
    }

    /**
     * Gets the value of the extSeverity property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExtSeverity() {
        return extSeverity;
    }

    /**
     * Sets the value of the extSeverity property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExtSeverity(String value) {
        this.extSeverity = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link BusinessimpactTypeType }
     *     
     */
    public BusinessimpactTypeType getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link BusinessimpactTypeType }
     *     
     */
    public void setType(BusinessimpactTypeType value) {
        this.type = value;
    }

    /**
     * Gets the value of the extType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExtType() {
        return extType;
    }

    /**
     * Sets the value of the extType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExtType(String value) {
        this.extType = value;
    }

}
