//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.23 at 09:39:40 PM JST 
//


package ietf.params.xml.ns.iodef_2;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for businessimpact-type-type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="businessimpact-type-type"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN"&gt;
 *     &lt;enumeration value="breach-proprietary"/&gt;
 *     &lt;enumeration value="breach-privacy"/&gt;
 *     &lt;enumeration value="breach-credential"/&gt;
 *     &lt;enumeration value="loss-of-integrity"/&gt;
 *     &lt;enumeration value="loss-of-service"/&gt;
 *     &lt;enumeration value="theft-financial"/&gt;
 *     &lt;enumeration value="theft-service"/&gt;
 *     &lt;enumeration value="degraded-reputation"/&gt;
 *     &lt;enumeration value="asset-damage"/&gt;
 *     &lt;enumeration value="asset-manipulation"/&gt;
 *     &lt;enumeration value="legal"/&gt;
 *     &lt;enumeration value="extortion"/&gt;
 *     &lt;enumeration value="ext-value"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "businessimpact-type-type")
@XmlEnum
public enum BusinessimpactTypeType {

    @XmlEnumValue("breach-proprietary")
    BREACH_PROPRIETARY("breach-proprietary"),
    @XmlEnumValue("breach-privacy")
    BREACH_PRIVACY("breach-privacy"),
    @XmlEnumValue("breach-credential")
    BREACH_CREDENTIAL("breach-credential"),
    @XmlEnumValue("loss-of-integrity")
    LOSS_OF_INTEGRITY("loss-of-integrity"),
    @XmlEnumValue("loss-of-service")
    LOSS_OF_SERVICE("loss-of-service"),
    @XmlEnumValue("theft-financial")
    THEFT_FINANCIAL("theft-financial"),
    @XmlEnumValue("theft-service")
    THEFT_SERVICE("theft-service"),
    @XmlEnumValue("degraded-reputation")
    DEGRADED_REPUTATION("degraded-reputation"),
    @XmlEnumValue("asset-damage")
    ASSET_DAMAGE("asset-damage"),
    @XmlEnumValue("asset-manipulation")
    ASSET_MANIPULATION("asset-manipulation"),
    @XmlEnumValue("legal")
    LEGAL("legal"),
    @XmlEnumValue("extortion")
    EXTORTION("extortion"),
    @XmlEnumValue("ext-value")
    EXT_VALUE("ext-value");
    private final String value;

    BusinessimpactTypeType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static BusinessimpactTypeType fromValue(String v) {
        for (BusinessimpactTypeType c: BusinessimpactTypeType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
