//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.23 at 09:39:40 PM JST 
//


package ietf.params.xml.ns.iodef_2;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for counter-type-type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="counter-type-type"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN"&gt;
 *     &lt;enumeration value="counter"/&gt;
 *     &lt;enumeration value="rate"/&gt;
 *     &lt;enumeration value="average"/&gt;
 *     &lt;enumeration value="ext-value"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "counter-type-type")
@XmlEnum
public enum CounterTypeType {

    @XmlEnumValue("counter")
    COUNTER("counter"),
    @XmlEnumValue("rate")
    RATE("rate"),
    @XmlEnumValue("average")
    AVERAGE("average"),
    @XmlEnumValue("ext-value")
    EXT_VALUE("ext-value");
    private final String value;

    CounterTypeType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static CounterTypeType fromValue(String v) {
        for (CounterTypeType c: CounterTypeType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
