//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.23 at 09:39:40 PM JST 
//


package ietf.params.xml.ns.iodef_2;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for discovery-source-type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="discovery-source-type"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN"&gt;
 *     &lt;enumeration value="nidps"/&gt;
 *     &lt;enumeration value="hips"/&gt;
 *     &lt;enumeration value="siem"/&gt;
 *     &lt;enumeration value="av"/&gt;
 *     &lt;enumeration value="third-party-monitoring"/&gt;
 *     &lt;enumeration value="incident"/&gt;
 *     &lt;enumeration value="os-log"/&gt;
 *     &lt;enumeration value="application-log"/&gt;
 *     &lt;enumeration value="device-log"/&gt;
 *     &lt;enumeration value="network-flow"/&gt;
 *     &lt;enumeration value="passive-dns"/&gt;
 *     &lt;enumeration value="investigation"/&gt;
 *     &lt;enumeration value="audit"/&gt;
 *     &lt;enumeration value="internal-notification"/&gt;
 *     &lt;enumeration value="external-notification"/&gt;
 *     &lt;enumeration value="leo"/&gt;
 *     &lt;enumeration value="partner"/&gt;
 *     &lt;enumeration value="actor"/&gt;
 *     &lt;enumeration value="unknown"/&gt;
 *     &lt;enumeration value="ext-value"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "discovery-source-type")
@XmlEnum
public enum DiscoverySourceType {

    @XmlEnumValue("nidps")
    NIDPS("nidps"),
    @XmlEnumValue("hips")
    HIPS("hips"),
    @XmlEnumValue("siem")
    SIEM("siem"),
    @XmlEnumValue("av")
    AV("av"),
    @XmlEnumValue("third-party-monitoring")
    THIRD_PARTY_MONITORING("third-party-monitoring"),
    @XmlEnumValue("incident")
    INCIDENT("incident"),
    @XmlEnumValue("os-log")
    OS_LOG("os-log"),
    @XmlEnumValue("application-log")
    APPLICATION_LOG("application-log"),
    @XmlEnumValue("device-log")
    DEVICE_LOG("device-log"),
    @XmlEnumValue("network-flow")
    NETWORK_FLOW("network-flow"),
    @XmlEnumValue("passive-dns")
    PASSIVE_DNS("passive-dns"),
    @XmlEnumValue("investigation")
    INVESTIGATION("investigation"),
    @XmlEnumValue("audit")
    AUDIT("audit"),
    @XmlEnumValue("internal-notification")
    INTERNAL_NOTIFICATION("internal-notification"),
    @XmlEnumValue("external-notification")
    EXTERNAL_NOTIFICATION("external-notification"),
    @XmlEnumValue("leo")
    LEO("leo"),
    @XmlEnumValue("partner")
    PARTNER("partner"),
    @XmlEnumValue("actor")
    ACTOR("actor"),
    @XmlEnumValue("unknown")
    UNKNOWN("unknown"),
    @XmlEnumValue("ext-value")
    EXT_VALUE("ext-value");
    private final String value;

    DiscoverySourceType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static DiscoverySourceType fromValue(String v) {
        for (DiscoverySourceType c: DiscoverySourceType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
