//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.23 at 09:39:40 PM JST 
//


package ietf.params.xml.ns.iodef_2;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{urn:ietf:params:xml:ns:iodef-2.0}Name"/&gt;
 *         &lt;element ref="{urn:ietf:params:xml:ns:iodef-2.0}DateDomainWasChecked" minOccurs="0"/&gt;
 *         &lt;element ref="{urn:ietf:params:xml:ns:iodef-2.0}RegistrationDate" minOccurs="0"/&gt;
 *         &lt;element ref="{urn:ietf:params:xml:ns:iodef-2.0}ExpirationDate" minOccurs="0"/&gt;
 *         &lt;element ref="{urn:ietf:params:xml:ns:iodef-2.0}RelatedDNS" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{urn:ietf:params:xml:ns:iodef-2.0}Nameservers" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{urn:ietf:params:xml:ns:iodef-2.0}DomainContacts" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="system-status" type="{urn:ietf:params:xml:ns:iodef-2.0}domaindata-system-status-type" /&gt;
 *       &lt;attribute name="ext-system-status" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="domain-status" type="{urn:ietf:params:xml:ns:iodef-2.0}domaindata-domain-status-type" /&gt;
 *       &lt;attribute name="ext-domain-status" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="observable-id" type="{http://www.w3.org/2001/XMLSchema}ID" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "name",
    "dateDomainWasChecked",
    "registrationDate",
    "expirationDate",
    "relatedDNS",
    "nameservers",
    "domainContacts"
})
@XmlRootElement(name = "DomainData")
public class DomainData {

    @XmlElement(name = "Name", required = true)
    protected String name;
    @XmlElement(name = "DateDomainWasChecked")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar dateDomainWasChecked;
    @XmlElement(name = "RegistrationDate")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar registrationDate;
    @XmlElement(name = "ExpirationDate")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar expirationDate;
    @XmlElement(name = "RelatedDNS")
    protected List<RelatedDNS> relatedDNS;
    @XmlElement(name = "Nameservers")
    protected List<Nameservers> nameservers;
    @XmlElement(name = "DomainContacts")
    protected DomainContacts domainContacts;
    @XmlAttribute(name = "system-status")
    protected DomaindataSystemStatusType systemStatus;
    @XmlAttribute(name = "ext-system-status")
    protected String extSystemStatus;
    @XmlAttribute(name = "domain-status")
    protected DomaindataDomainStatusType domainStatus;
    @XmlAttribute(name = "ext-domain-status")
    protected String extDomainStatus;
    @XmlAttribute(name = "observable-id")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected String observableId;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the dateDomainWasChecked property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDateDomainWasChecked() {
        return dateDomainWasChecked;
    }

    /**
     * Sets the value of the dateDomainWasChecked property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDateDomainWasChecked(XMLGregorianCalendar value) {
        this.dateDomainWasChecked = value;
    }

    /**
     * Gets the value of the registrationDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getRegistrationDate() {
        return registrationDate;
    }

    /**
     * Sets the value of the registrationDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setRegistrationDate(XMLGregorianCalendar value) {
        this.registrationDate = value;
    }

    /**
     * Gets the value of the expirationDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getExpirationDate() {
        return expirationDate;
    }

    /**
     * Sets the value of the expirationDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setExpirationDate(XMLGregorianCalendar value) {
        this.expirationDate = value;
    }

    /**
     * Gets the value of the relatedDNS property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the relatedDNS property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRelatedDNS().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RelatedDNS }
     * 
     * 
     */
    public List<RelatedDNS> getRelatedDNS() {
        if (relatedDNS == null) {
            relatedDNS = new ArrayList<RelatedDNS>();
        }
        return this.relatedDNS;
    }

    /**
     * Gets the value of the nameservers property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the nameservers property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNameservers().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Nameservers }
     * 
     * 
     */
    public List<Nameservers> getNameservers() {
        if (nameservers == null) {
            nameservers = new ArrayList<Nameservers>();
        }
        return this.nameservers;
    }

    /**
     * Gets the value of the domainContacts property.
     * 
     * @return
     *     possible object is
     *     {@link DomainContacts }
     *     
     */
    public DomainContacts getDomainContacts() {
        return domainContacts;
    }

    /**
     * Sets the value of the domainContacts property.
     * 
     * @param value
     *     allowed object is
     *     {@link DomainContacts }
     *     
     */
    public void setDomainContacts(DomainContacts value) {
        this.domainContacts = value;
    }

    /**
     * Gets the value of the systemStatus property.
     * 
     * @return
     *     possible object is
     *     {@link DomaindataSystemStatusType }
     *     
     */
    public DomaindataSystemStatusType getSystemStatus() {
        return systemStatus;
    }

    /**
     * Sets the value of the systemStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link DomaindataSystemStatusType }
     *     
     */
    public void setSystemStatus(DomaindataSystemStatusType value) {
        this.systemStatus = value;
    }

    /**
     * Gets the value of the extSystemStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExtSystemStatus() {
        return extSystemStatus;
    }

    /**
     * Sets the value of the extSystemStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExtSystemStatus(String value) {
        this.extSystemStatus = value;
    }

    /**
     * Gets the value of the domainStatus property.
     * 
     * @return
     *     possible object is
     *     {@link DomaindataDomainStatusType }
     *     
     */
    public DomaindataDomainStatusType getDomainStatus() {
        return domainStatus;
    }

    /**
     * Sets the value of the domainStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link DomaindataDomainStatusType }
     *     
     */
    public void setDomainStatus(DomaindataDomainStatusType value) {
        this.domainStatus = value;
    }

    /**
     * Gets the value of the extDomainStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExtDomainStatus() {
        return extDomainStatus;
    }

    /**
     * Sets the value of the extDomainStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExtDomainStatus(String value) {
        this.extDomainStatus = value;
    }

    /**
     * Gets the value of the observableId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getObservableId() {
        return observableId;
    }

    /**
     * Sets the value of the observableId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setObservableId(String value) {
        this.observableId = value;
    }

}
