//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.23 at 09:39:40 PM JST 
//


package ietf.params.xml.ns.iodef_2;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for domaindata-system-status-type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="domaindata-system-status-type"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="spoofed"/&gt;
 *     &lt;enumeration value="fraudulent"/&gt;
 *     &lt;enumeration value="innocent-hacked"/&gt;
 *     &lt;enumeration value="innocent-hijacked"/&gt;
 *     &lt;enumeration value="unknown"/&gt;
 *     &lt;enumeration value="ext-value"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "domaindata-system-status-type")
@XmlEnum
public enum DomaindataSystemStatusType {

    @XmlEnumValue("spoofed")
    SPOOFED("spoofed"),
    @XmlEnumValue("fraudulent")
    FRAUDULENT("fraudulent"),
    @XmlEnumValue("innocent-hacked")
    INNOCENT_HACKED("innocent-hacked"),
    @XmlEnumValue("innocent-hijacked")
    INNOCENT_HIJACKED("innocent-hijacked"),
    @XmlEnumValue("unknown")
    UNKNOWN("unknown"),
    @XmlEnumValue("ext-value")
    EXT_VALUE("ext-value");
    private final String value;

    DomaindataSystemStatusType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static DomaindataSystemStatusType fromValue(String v) {
        for (DomaindataSystemStatusType c: DomaindataSystemStatusType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
