//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.23 at 09:39:40 PM JST 
//


package ietf.params.xml.ns.iodef_2;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for domaindata-domain-status-type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="domaindata-domain-status-type"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="reservedDelegation"/&gt;
 *     &lt;enumeration value="assignedAndActive"/&gt;
 *     &lt;enumeration value="assignedAndInactive"/&gt;
 *     &lt;enumeration value="assignedAndOnHold"/&gt;
 *     &lt;enumeration value="revoked"/&gt;
 *     &lt;enumeration value="transferPending"/&gt;
 *     &lt;enumeration value="registryLock"/&gt;
 *     &lt;enumeration value="registrarLock"/&gt;
 *     &lt;enumeration value="other"/&gt;
 *     &lt;enumeration value="unknown"/&gt;
 *     &lt;enumeration value="ext-value"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "domaindata-domain-status-type")
@XmlEnum
public enum DomaindataDomainStatusType {

    @XmlEnumValue("reservedDelegation")
    RESERVED_DELEGATION("reservedDelegation"),
    @XmlEnumValue("assignedAndActive")
    ASSIGNED_AND_ACTIVE("assignedAndActive"),
    @XmlEnumValue("assignedAndInactive")
    ASSIGNED_AND_INACTIVE("assignedAndInactive"),
    @XmlEnumValue("assignedAndOnHold")
    ASSIGNED_AND_ON_HOLD("assignedAndOnHold"),
    @XmlEnumValue("revoked")
    REVOKED("revoked"),
    @XmlEnumValue("transferPending")
    TRANSFER_PENDING("transferPending"),
    @XmlEnumValue("registryLock")
    REGISTRY_LOCK("registryLock"),
    @XmlEnumValue("registrarLock")
    REGISTRAR_LOCK("registrarLock"),
    @XmlEnumValue("other")
    OTHER("other"),
    @XmlEnumValue("unknown")
    UNKNOWN("unknown"),
    @XmlEnumValue("ext-value")
    EXT_VALUE("ext-value");
    private final String value;

    DomaindataDomainStatusType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static DomaindataDomainStatusType fromValue(String v) {
        for (DomaindataDomainStatusType c: DomaindataDomainStatusType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
