//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.23 at 09:39:40 PM JST 
//


package ietf.params.xml.ns.iodef_2;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{urn:ietf:params:xml:ns:iodef-2.0}EmailFrom" minOccurs="0"/&gt;
 *         &lt;element ref="{urn:ietf:params:xml:ns:iodef-2.0}EmailSubject" minOccurs="0"/&gt;
 *         &lt;element ref="{urn:ietf:params:xml:ns:iodef-2.0}EmailX-Mailer" minOccurs="0"/&gt;
 *         &lt;element ref="{urn:ietf:params:xml:ns:iodef-2.0}EmailHeaderField" minOccurs="0"/&gt;
 *         &lt;element ref="{urn:ietf:params:xml:ns:iodef-2.0}HashData" minOccurs="0"/&gt;
 *         &lt;element ref="{urn:ietf:params:xml:ns:iodef-2.0}SignatureData" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="observable-id" type="{http://www.w3.org/2001/XMLSchema}ID" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "emailFrom",
    "emailSubject",
    "emailXMailer",
    "emailHeaderField",
    "hashData",
    "signatureData"
})
@XmlRootElement(name = "EmailData")
public class EmailData {

    @XmlElement(name = "EmailFrom")
    protected MLStringType emailFrom;
    @XmlElement(name = "EmailSubject")
    protected MLStringType emailSubject;
    @XmlElement(name = "EmailX-Mailer")
    protected MLStringType emailXMailer;
    @XmlElement(name = "EmailHeaderField")
    protected ApplicationHeaderType emailHeaderField;
    @XmlElement(name = "HashData")
    protected HashData hashData;
    @XmlElement(name = "SignatureData")
    protected SignatureData signatureData;
    @XmlAttribute(name = "observable-id")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected String observableId;

    /**
     * Gets the value of the emailFrom property.
     * 
     * @return
     *     possible object is
     *     {@link MLStringType }
     *     
     */
    public MLStringType getEmailFrom() {
        return emailFrom;
    }

    /**
     * Sets the value of the emailFrom property.
     * 
     * @param value
     *     allowed object is
     *     {@link MLStringType }
     *     
     */
    public void setEmailFrom(MLStringType value) {
        this.emailFrom = value;
    }

    /**
     * Gets the value of the emailSubject property.
     * 
     * @return
     *     possible object is
     *     {@link MLStringType }
     *     
     */
    public MLStringType getEmailSubject() {
        return emailSubject;
    }

    /**
     * Sets the value of the emailSubject property.
     * 
     * @param value
     *     allowed object is
     *     {@link MLStringType }
     *     
     */
    public void setEmailSubject(MLStringType value) {
        this.emailSubject = value;
    }

    /**
     * Gets the value of the emailXMailer property.
     * 
     * @return
     *     possible object is
     *     {@link MLStringType }
     *     
     */
    public MLStringType getEmailXMailer() {
        return emailXMailer;
    }

    /**
     * Sets the value of the emailXMailer property.
     * 
     * @param value
     *     allowed object is
     *     {@link MLStringType }
     *     
     */
    public void setEmailXMailer(MLStringType value) {
        this.emailXMailer = value;
    }

    /**
     * Gets the value of the emailHeaderField property.
     * 
     * @return
     *     possible object is
     *     {@link ApplicationHeaderType }
     *     
     */
    public ApplicationHeaderType getEmailHeaderField() {
        return emailHeaderField;
    }

    /**
     * Sets the value of the emailHeaderField property.
     * 
     * @param value
     *     allowed object is
     *     {@link ApplicationHeaderType }
     *     
     */
    public void setEmailHeaderField(ApplicationHeaderType value) {
        this.emailHeaderField = value;
    }

    /**
     * Gets the value of the hashData property.
     * 
     * @return
     *     possible object is
     *     {@link HashData }
     *     
     */
    public HashData getHashData() {
        return hashData;
    }

    /**
     * Sets the value of the hashData property.
     * 
     * @param value
     *     allowed object is
     *     {@link HashData }
     *     
     */
    public void setHashData(HashData value) {
        this.hashData = value;
    }

    /**
     * Gets the value of the signatureData property.
     * 
     * @return
     *     possible object is
     *     {@link SignatureData }
     *     
     */
    public SignatureData getSignatureData() {
        return signatureData;
    }

    /**
     * Sets the value of the signatureData property.
     * 
     * @param value
     *     allowed object is
     *     {@link SignatureData }
     *     
     */
    public void setSignatureData(SignatureData value) {
        this.signatureData = value;
    }

    /**
     * Gets the value of the observableId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getObservableId() {
        return observableId;
    }

    /**
     * Sets the value of the observableId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setObservableId(String value) {
        this.observableId = value;
    }

}
