//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.23 at 09:39:40 PM JST 
//


package ietf.params.xml.ns.iodef_2;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for hashdata-scope-type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="hashdata-scope-type"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN"&gt;
 *     &lt;enumeration value="file-contents"/&gt;
 *     &lt;enumeration value="file-pe-section"/&gt;
 *     &lt;enumeration value="file-pe-iat"/&gt;
 *     &lt;enumeration value="file-pe-resource"/&gt;
 *     &lt;enumeration value="file-pdf-object"/&gt;
 *     &lt;enumeration value="email-hash"/&gt;
 *     &lt;enumeration value="email-headers-hash"/&gt;
 *     &lt;enumeration value="email-body-hash"/&gt;
 *     &lt;enumeration value="ext-value"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "hashdata-scope-type")
@XmlEnum
public enum HashdataScopeType {

    @XmlEnumValue("file-contents")
    FILE_CONTENTS("file-contents"),
    @XmlEnumValue("file-pe-section")
    FILE_PE_SECTION("file-pe-section"),
    @XmlEnumValue("file-pe-iat")
    FILE_PE_IAT("file-pe-iat"),
    @XmlEnumValue("file-pe-resource")
    FILE_PE_RESOURCE("file-pe-resource"),
    @XmlEnumValue("file-pdf-object")
    FILE_PDF_OBJECT("file-pdf-object"),
    @XmlEnumValue("email-hash")
    EMAIL_HASH("email-hash"),
    @XmlEnumValue("email-headers-hash")
    EMAIL_HEADERS_HASH("email-headers-hash"),
    @XmlEnumValue("email-body-hash")
    EMAIL_BODY_HASH("email-body-hash"),
    @XmlEnumValue("ext-value")
    EXT_VALUE("ext-value");
    private final String value;

    HashdataScopeType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static HashdataScopeType fromValue(String v) {
        for (HashdataScopeType c: HashdataScopeType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
