//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.23 at 09:39:40 PM JST 
//


package ietf.params.xml.ns.iodef_2;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{urn:ietf:params:xml:ns:iodef-2.0}HashTarget" minOccurs="0"/&gt;
 *         &lt;element ref="{urn:ietf:params:xml:ns:iodef-2.0}Hash" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{urn:ietf:params:xml:ns:iodef-2.0}FuzzyHash" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="scope" use="required" type="{urn:ietf:params:xml:ns:iodef-2.0}hashdata-scope-type" /&gt;
 *       &lt;attribute name="ext-scope" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "hashTarget",
    "hash",
    "fuzzyHash"
})
@XmlRootElement(name = "HashData")
public class HashData {

    @XmlElement(name = "HashTarget")
    protected MLStringType hashTarget;
    @XmlElement(name = "Hash")
    protected List<Hash> hash;
    @XmlElement(name = "FuzzyHash")
    protected List<FuzzyHash> fuzzyHash;
    @XmlAttribute(name = "scope", required = true)
    protected HashdataScopeType scope;
    @XmlAttribute(name = "ext-scope")
    protected String extScope;

    /**
     * Gets the value of the hashTarget property.
     * 
     * @return
     *     possible object is
     *     {@link MLStringType }
     *     
     */
    public MLStringType getHashTarget() {
        return hashTarget;
    }

    /**
     * Sets the value of the hashTarget property.
     * 
     * @param value
     *     allowed object is
     *     {@link MLStringType }
     *     
     */
    public void setHashTarget(MLStringType value) {
        this.hashTarget = value;
    }

    /**
     * Gets the value of the hash property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the hash property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getHash().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Hash }
     * 
     * 
     */
    public List<Hash> getHash() {
        if (hash == null) {
            hash = new ArrayList<Hash>();
        }
        return this.hash;
    }

    /**
     * Gets the value of the fuzzyHash property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the fuzzyHash property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFuzzyHash().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link FuzzyHash }
     * 
     * 
     */
    public List<FuzzyHash> getFuzzyHash() {
        if (fuzzyHash == null) {
            fuzzyHash = new ArrayList<FuzzyHash>();
        }
        return this.fuzzyHash;
    }

    /**
     * Gets the value of the scope property.
     * 
     * @return
     *     possible object is
     *     {@link HashdataScopeType }
     *     
     */
    public HashdataScopeType getScope() {
        return scope;
    }

    /**
     * Sets the value of the scope property.
     * 
     * @param value
     *     allowed object is
     *     {@link HashdataScopeType }
     *     
     */
    public void setScope(HashdataScopeType value) {
        this.scope = value;
    }

    /**
     * Gets the value of the extScope property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExtScope() {
        return extScope;
    }

    /**
     * Sets the value of the extScope property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExtScope(String value) {
        this.extScope = value;
    }

}
