//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.23 at 09:39:40 PM JST 
//


package ietf.params.xml.ns.iodef_2;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for incident-status-type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="incident-status-type"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN"&gt;
 *     &lt;enumeration value="new"/&gt;
 *     &lt;enumeration value="in-progress"/&gt;
 *     &lt;enumeration value="forwarded"/&gt;
 *     &lt;enumeration value="resolved"/&gt;
 *     &lt;enumeration value="future"/&gt;
 *     &lt;enumeration value="ext-value"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "incident-status-type")
@XmlEnum
public enum IncidentStatusType {

    @XmlEnumValue("new")
    NEW("new"),
    @XmlEnumValue("in-progress")
    IN_PROGRESS("in-progress"),
    @XmlEnumValue("forwarded")
    FORWARDED("forwarded"),
    @XmlEnumValue("resolved")
    RESOLVED("resolved"),
    @XmlEnumValue("future")
    FUTURE("future"),
    @XmlEnumValue("ext-value")
    EXT_VALUE("ext-value");
    private final String value;

    IncidentStatusType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static IncidentStatusType fromValue(String v) {
        for (IncidentStatusType c: IncidentStatusType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
