//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.23 at 09:39:40 PM JST 
//


package ietf.params.xml.ns.iodef_2;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{urn:ietf:params:xml:ns:iodef-2.0}IndicatorID"/&gt;
 *         &lt;element ref="{urn:ietf:params:xml:ns:iodef-2.0}AlternativeIndicatorID" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{urn:ietf:params:xml:ns:iodef-2.0}Description" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{urn:ietf:params:xml:ns:iodef-2.0}StartTime" minOccurs="0"/&gt;
 *         &lt;element ref="{urn:ietf:params:xml:ns:iodef-2.0}EndTime" minOccurs="0"/&gt;
 *         &lt;element ref="{urn:ietf:params:xml:ns:iodef-2.0}Confidence" minOccurs="0"/&gt;
 *         &lt;element ref="{urn:ietf:params:xml:ns:iodef-2.0}Contact" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;choice&gt;
 *           &lt;element ref="{urn:ietf:params:xml:ns:iodef-2.0}Observable"/&gt;
 *           &lt;element ref="{urn:ietf:params:xml:ns:iodef-2.0}ObservableReference"/&gt;
 *           &lt;element ref="{urn:ietf:params:xml:ns:iodef-2.0}IndicatorExpression"/&gt;
 *           &lt;element ref="{urn:ietf:params:xml:ns:iodef-2.0}IndicatorReference"/&gt;
 *         &lt;/choice&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="restriction" type="{urn:ietf:params:xml:ns:iodef-2.0}restriction-type" /&gt;
 *       &lt;attribute name="ext-restriction" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "indicatorID",
    "alternativeIndicatorID",
    "description",
    "startTime",
    "endTime",
    "confidence",
    "contact",
    "observable",
    "observableReference",
    "indicatorExpression",
    "indicatorReference"
})
@XmlRootElement(name = "Indicator")
public class Indicator {

    @XmlElement(name = "IndicatorID", required = true)
    protected IndicatorID indicatorID;
    @XmlElement(name = "AlternativeIndicatorID")
    protected List<AlternativeIndicatorID> alternativeIndicatorID;
    @XmlElement(name = "Description")
    protected List<MLStringType> description;
    @XmlElement(name = "StartTime")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar startTime;
    @XmlElement(name = "EndTime")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar endTime;
    @XmlElement(name = "Confidence")
    protected Confidence confidence;
    @XmlElement(name = "Contact")
    protected List<Contact> contact;
    @XmlElement(name = "Observable")
    protected Observable observable;
    @XmlElement(name = "ObservableReference")
    protected ObservableReference observableReference;
    @XmlElement(name = "IndicatorExpression")
    protected IndicatorExpression indicatorExpression;
    @XmlElement(name = "IndicatorReference")
    protected IndicatorReference indicatorReference;
    @XmlAttribute(name = "restriction")
    protected RestrictionType restriction;
    @XmlAttribute(name = "ext-restriction")
    protected String extRestriction;

    /**
     * Gets the value of the indicatorID property.
     * 
     * @return
     *     possible object is
     *     {@link IndicatorID }
     *     
     */
    public IndicatorID getIndicatorID() {
        return indicatorID;
    }

    /**
     * Sets the value of the indicatorID property.
     * 
     * @param value
     *     allowed object is
     *     {@link IndicatorID }
     *     
     */
    public void setIndicatorID(IndicatorID value) {
        this.indicatorID = value;
    }

    /**
     * Gets the value of the alternativeIndicatorID property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the alternativeIndicatorID property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAlternativeIndicatorID().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AlternativeIndicatorID }
     * 
     * 
     */
    public List<AlternativeIndicatorID> getAlternativeIndicatorID() {
        if (alternativeIndicatorID == null) {
            alternativeIndicatorID = new ArrayList<AlternativeIndicatorID>();
        }
        return this.alternativeIndicatorID;
    }

    /**
     * Gets the value of the description property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the description property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDescription().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MLStringType }
     * 
     * 
     */
    public List<MLStringType> getDescription() {
        if (description == null) {
            description = new ArrayList<MLStringType>();
        }
        return this.description;
    }

    /**
     * Gets the value of the startTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getStartTime() {
        return startTime;
    }

    /**
     * Sets the value of the startTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setStartTime(XMLGregorianCalendar value) {
        this.startTime = value;
    }

    /**
     * Gets the value of the endTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getEndTime() {
        return endTime;
    }

    /**
     * Sets the value of the endTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setEndTime(XMLGregorianCalendar value) {
        this.endTime = value;
    }

    /**
     * Gets the value of the confidence property.
     * 
     * @return
     *     possible object is
     *     {@link Confidence }
     *     
     */
    public Confidence getConfidence() {
        return confidence;
    }

    /**
     * Sets the value of the confidence property.
     * 
     * @param value
     *     allowed object is
     *     {@link Confidence }
     *     
     */
    public void setConfidence(Confidence value) {
        this.confidence = value;
    }

    /**
     * Gets the value of the contact property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the contact property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getContact().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Contact }
     * 
     * 
     */
    public List<Contact> getContact() {
        if (contact == null) {
            contact = new ArrayList<Contact>();
        }
        return this.contact;
    }

    /**
     * Gets the value of the observable property.
     * 
     * @return
     *     possible object is
     *     {@link Observable }
     *     
     */
    public Observable getObservable() {
        return observable;
    }

    /**
     * Sets the value of the observable property.
     * 
     * @param value
     *     allowed object is
     *     {@link Observable }
     *     
     */
    public void setObservable(Observable value) {
        this.observable = value;
    }

    /**
     * Gets the value of the observableReference property.
     * 
     * @return
     *     possible object is
     *     {@link ObservableReference }
     *     
     */
    public ObservableReference getObservableReference() {
        return observableReference;
    }

    /**
     * Sets the value of the observableReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link ObservableReference }
     *     
     */
    public void setObservableReference(ObservableReference value) {
        this.observableReference = value;
    }

    /**
     * Gets the value of the indicatorExpression property.
     * 
     * @return
     *     possible object is
     *     {@link IndicatorExpression }
     *     
     */
    public IndicatorExpression getIndicatorExpression() {
        return indicatorExpression;
    }

    /**
     * Sets the value of the indicatorExpression property.
     * 
     * @param value
     *     allowed object is
     *     {@link IndicatorExpression }
     *     
     */
    public void setIndicatorExpression(IndicatorExpression value) {
        this.indicatorExpression = value;
    }

    /**
     * Gets the value of the indicatorReference property.
     * 
     * @return
     *     possible object is
     *     {@link IndicatorReference }
     *     
     */
    public IndicatorReference getIndicatorReference() {
        return indicatorReference;
    }

    /**
     * Sets the value of the indicatorReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link IndicatorReference }
     *     
     */
    public void setIndicatorReference(IndicatorReference value) {
        this.indicatorReference = value;
    }

    /**
     * Gets the value of the restriction property.
     * 
     * @return
     *     possible object is
     *     {@link RestrictionType }
     *     
     */
    public RestrictionType getRestriction() {
        return restriction;
    }

    /**
     * Sets the value of the restriction property.
     * 
     * @param value
     *     allowed object is
     *     {@link RestrictionType }
     *     
     */
    public void setRestriction(RestrictionType value) {
        this.restriction = value;
    }

    /**
     * Gets the value of the extRestriction property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExtRestriction() {
        return extRestriction;
    }

    /**
     * Sets the value of the extRestriction property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExtRestriction(String value) {
        this.extRestriction = value;
    }

}
