//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.23 at 09:39:40 PM JST 
//


package ietf.params.xml.ns.iodef_2;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;choice&gt;
 *           &lt;element ref="{urn:ietf:params:xml:ns:iodef-2.0}IndicatorExpression" minOccurs="0"/&gt;
 *           &lt;element ref="{urn:ietf:params:xml:ns:iodef-2.0}Observable" minOccurs="0"/&gt;
 *           &lt;element ref="{urn:ietf:params:xml:ns:iodef-2.0}ObservableReference" minOccurs="0"/&gt;
 *           &lt;element ref="{urn:ietf:params:xml:ns:iodef-2.0}IndicatorReference" minOccurs="0"/&gt;
 *         &lt;/choice&gt;
 *         &lt;element ref="{urn:ietf:params:xml:ns:iodef-2.0}AlternativeIndicatorID" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="operator" use="required" type="{urn:ietf:params:xml:ns:iodef-2.0}indicatorexpression-operator-type" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "indicatorExpression",
    "observable",
    "observableReference",
    "indicatorReference",
    "alternativeIndicatorID"
})
@XmlRootElement(name = "IndicatorExpression")
public class IndicatorExpression {

    @XmlElement(name = "IndicatorExpression")
    protected IndicatorExpression indicatorExpression;
    @XmlElement(name = "Observable")
    protected Observable observable;
    @XmlElement(name = "ObservableReference")
    protected ObservableReference observableReference;
    @XmlElement(name = "IndicatorReference")
    protected IndicatorReference indicatorReference;
    @XmlElement(name = "AlternativeIndicatorID")
    protected List<AlternativeIndicatorID> alternativeIndicatorID;
    @XmlAttribute(name = "operator", required = true)
    protected IndicatorexpressionOperatorType operator;

    /**
     * Gets the value of the indicatorExpression property.
     * 
     * @return
     *     possible object is
     *     {@link IndicatorExpression }
     *     
     */
    public IndicatorExpression getIndicatorExpression() {
        return indicatorExpression;
    }

    /**
     * Sets the value of the indicatorExpression property.
     * 
     * @param value
     *     allowed object is
     *     {@link IndicatorExpression }
     *     
     */
    public void setIndicatorExpression(IndicatorExpression value) {
        this.indicatorExpression = value;
    }

    /**
     * Gets the value of the observable property.
     * 
     * @return
     *     possible object is
     *     {@link Observable }
     *     
     */
    public Observable getObservable() {
        return observable;
    }

    /**
     * Sets the value of the observable property.
     * 
     * @param value
     *     allowed object is
     *     {@link Observable }
     *     
     */
    public void setObservable(Observable value) {
        this.observable = value;
    }

    /**
     * Gets the value of the observableReference property.
     * 
     * @return
     *     possible object is
     *     {@link ObservableReference }
     *     
     */
    public ObservableReference getObservableReference() {
        return observableReference;
    }

    /**
     * Sets the value of the observableReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link ObservableReference }
     *     
     */
    public void setObservableReference(ObservableReference value) {
        this.observableReference = value;
    }

    /**
     * Gets the value of the indicatorReference property.
     * 
     * @return
     *     possible object is
     *     {@link IndicatorReference }
     *     
     */
    public IndicatorReference getIndicatorReference() {
        return indicatorReference;
    }

    /**
     * Sets the value of the indicatorReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link IndicatorReference }
     *     
     */
    public void setIndicatorReference(IndicatorReference value) {
        this.indicatorReference = value;
    }

    /**
     * Gets the value of the alternativeIndicatorID property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the alternativeIndicatorID property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAlternativeIndicatorID().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AlternativeIndicatorID }
     * 
     * 
     */
    public List<AlternativeIndicatorID> getAlternativeIndicatorID() {
        if (alternativeIndicatorID == null) {
            alternativeIndicatorID = new ArrayList<AlternativeIndicatorID>();
        }
        return this.alternativeIndicatorID;
    }

    /**
     * Gets the value of the operator property.
     * 
     * @return
     *     possible object is
     *     {@link IndicatorexpressionOperatorType }
     *     
     */
    public IndicatorexpressionOperatorType getOperator() {
        return operator;
    }

    /**
     * Sets the value of the operator property.
     * 
     * @param value
     *     allowed object is
     *     {@link IndicatorexpressionOperatorType }
     *     
     */
    public void setOperator(IndicatorexpressionOperatorType value) {
        this.operator = value;
    }

}
