//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.23 at 09:39:40 PM JST 
//


package ietf.params.xml.ns.iodef_2;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{urn:ietf:params:xml:ns:iodef-2.0}KeyName"/&gt;
 *         &lt;element ref="{urn:ietf:params:xml:ns:iodef-2.0}Value" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="registryaction" type="{urn:ietf:params:xml:ns:iodef-2.0}key-registryaction-type" /&gt;
 *       &lt;attribute name="ext-registryaction" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "keyName",
    "value"
})
@XmlRootElement(name = "Key")
public class Key {

    @XmlElement(name = "KeyName", required = true)
    protected String keyName;
    @XmlElement(name = "Value")
    protected String value;
    @XmlAttribute(name = "registryaction")
    protected KeyRegistryactionType registryaction;
    @XmlAttribute(name = "ext-registryaction")
    protected String extRegistryaction;

    /**
     * Gets the value of the keyName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKeyName() {
        return keyName;
    }

    /**
     * Sets the value of the keyName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKeyName(String value) {
        this.keyName = value;
    }

    /**
     * Gets the value of the value property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValue(String value) {
        this.value = value;
    }

    /**
     * Gets the value of the registryaction property.
     * 
     * @return
     *     possible object is
     *     {@link KeyRegistryactionType }
     *     
     */
    public KeyRegistryactionType getRegistryaction() {
        return registryaction;
    }

    /**
     * Sets the value of the registryaction property.
     * 
     * @param value
     *     allowed object is
     *     {@link KeyRegistryactionType }
     *     
     */
    public void setRegistryaction(KeyRegistryactionType value) {
        this.registryaction = value;
    }

    /**
     * Gets the value of the extRegistryaction property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExtRegistryaction() {
        return extRegistryaction;
    }

    /**
     * Sets the value of the extRegistryaction property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExtRegistryaction(String value) {
        this.extRegistryaction = value;
    }

}
