//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.23 at 09:39:40 PM JST 
//


package ietf.params.xml.ns.iodef_2;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for key-registryaction-type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="key-registryaction-type"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN"&gt;
 *     &lt;enumeration value="add-key"/&gt;
 *     &lt;enumeration value="add-value"/&gt;
 *     &lt;enumeration value="delete-key"/&gt;
 *     &lt;enumeration value="delete-value"/&gt;
 *     &lt;enumeration value="modify-key"/&gt;
 *     &lt;enumeration value="modify-value"/&gt;
 *     &lt;enumeration value="ext-value"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "key-registryaction-type")
@XmlEnum
public enum KeyRegistryactionType {

    @XmlEnumValue("add-key")
    ADD_KEY("add-key"),
    @XmlEnumValue("add-value")
    ADD_VALUE("add-value"),
    @XmlEnumValue("delete-key")
    DELETE_KEY("delete-key"),
    @XmlEnumValue("delete-value")
    DELETE_VALUE("delete-value"),
    @XmlEnumValue("modify-key")
    MODIFY_KEY("modify-key"),
    @XmlEnumValue("modify-value")
    MODIFY_VALUE("modify-value"),
    @XmlEnumValue("ext-value")
    EXT_VALUE("ext-value");
    private final String value;

    KeyRegistryactionType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static KeyRegistryactionType fromValue(String v) {
        for (KeyRegistryactionType c: KeyRegistryactionType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
