//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.23 at 09:39:40 PM JST 
//


package ietf.params.xml.ns.iodef_2;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{urn:ietf:params:xml:ns:iodef-2.0}Address" minOccurs="0"/&gt;
 *         &lt;element ref="{urn:ietf:params:xml:ns:iodef-2.0}DomainData" minOccurs="0"/&gt;
 *         &lt;element ref="{urn:ietf:params:xml:ns:iodef-2.0}EmailData" minOccurs="0"/&gt;
 *         &lt;element name="ApplicationHeader" type="{urn:ietf:params:xml:ns:iodef-2.0}ApplicationHeaderType" minOccurs="0"/&gt;
 *         &lt;element ref="{urn:ietf:params:xml:ns:iodef-2.0}WindowsRegistryKeysModified" minOccurs="0"/&gt;
 *         &lt;element ref="{urn:ietf:params:xml:ns:iodef-2.0}FileData" minOccurs="0"/&gt;
 *         &lt;element ref="{urn:ietf:params:xml:ns:iodef-2.0}CertificateData" minOccurs="0"/&gt;
 *         &lt;element ref="{urn:ietf:params:xml:ns:iodef-2.0}RegistryHandle" minOccurs="0"/&gt;
 *         &lt;element ref="{urn:ietf:params:xml:ns:iodef-2.0}RecordData" minOccurs="0"/&gt;
 *         &lt;element ref="{urn:ietf:params:xml:ns:iodef-2.0}EventData" minOccurs="0"/&gt;
 *         &lt;element ref="{urn:ietf:params:xml:ns:iodef-2.0}Incident" minOccurs="0"/&gt;
 *         &lt;element ref="{urn:ietf:params:xml:ns:iodef-2.0}Expectation" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{urn:ietf:params:xml:ns:iodef-2.0}Reference" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{urn:ietf:params:xml:ns:iodef-2.0}Assessment" minOccurs="0"/&gt;
 *         &lt;element ref="{urn:ietf:params:xml:ns:iodef-2.0}HistoryItem" minOccurs="0"/&gt;
 *         &lt;element ref="{urn:ietf:params:xml:ns:iodef-2.0}BulkObservable" minOccurs="0"/&gt;
 *         &lt;element ref="{urn:ietf:params:xml:ns:iodef-2.0}AdditionalData" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="restriction" type="{urn:ietf:params:xml:ns:iodef-2.0}restriction-type" /&gt;
 *       &lt;attribute name="ext-restriction" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "address",
    "domainData",
    "emailData",
    "applicationHeader",
    "windowsRegistryKeysModified",
    "fileData",
    "certificateData",
    "registryHandle",
    "recordData",
    "eventData",
    "incident",
    "expectation",
    "reference",
    "assessment",
    "historyItem",
    "bulkObservable",
    "additionalData"
})
@XmlRootElement(name = "Observable")
public class Observable {

    @XmlElement(name = "Address")
    protected Address address;
    @XmlElement(name = "DomainData")
    protected DomainData domainData;
    @XmlElement(name = "EmailData")
    protected EmailData emailData;
    @XmlElement(name = "ApplicationHeader")
    protected ApplicationHeaderType applicationHeader;
    @XmlElement(name = "WindowsRegistryKeysModified")
    protected WindowsRegistryKeysModified windowsRegistryKeysModified;
    @XmlElement(name = "FileData")
    protected FileData fileData;
    @XmlElement(name = "CertificateData")
    protected CertificateData certificateData;
    @XmlElement(name = "RegistryHandle")
    protected RegistryHandle registryHandle;
    @XmlElement(name = "RecordData")
    protected RecordData recordData;
    @XmlElement(name = "EventData")
    protected EventData eventData;
    @XmlElement(name = "Incident")
    protected Incident incident;
    @XmlElement(name = "Expectation")
    protected List<Expectation> expectation;
    @XmlElement(name = "Reference")
    protected List<Reference> reference;
    @XmlElement(name = "Assessment")
    protected Assessment assessment;
    @XmlElement(name = "HistoryItem")
    protected HistoryItem historyItem;
    @XmlElement(name = "BulkObservable")
    protected BulkObservable bulkObservable;
    @XmlElement(name = "AdditionalData")
    protected ExtensionType additionalData;
    @XmlAttribute(name = "restriction")
    protected RestrictionType restriction;
    @XmlAttribute(name = "ext-restriction")
    protected String extRestriction;

    /**
     * Gets the value of the address property.
     * 
     * @return
     *     possible object is
     *     {@link Address }
     *     
     */
    public Address getAddress() {
        return address;
    }

    /**
     * Sets the value of the address property.
     * 
     * @param value
     *     allowed object is
     *     {@link Address }
     *     
     */
    public void setAddress(Address value) {
        this.address = value;
    }

    /**
     * Gets the value of the domainData property.
     * 
     * @return
     *     possible object is
     *     {@link DomainData }
     *     
     */
    public DomainData getDomainData() {
        return domainData;
    }

    /**
     * Sets the value of the domainData property.
     * 
     * @param value
     *     allowed object is
     *     {@link DomainData }
     *     
     */
    public void setDomainData(DomainData value) {
        this.domainData = value;
    }

    /**
     * Gets the value of the emailData property.
     * 
     * @return
     *     possible object is
     *     {@link EmailData }
     *     
     */
    public EmailData getEmailData() {
        return emailData;
    }

    /**
     * Sets the value of the emailData property.
     * 
     * @param value
     *     allowed object is
     *     {@link EmailData }
     *     
     */
    public void setEmailData(EmailData value) {
        this.emailData = value;
    }

    /**
     * Gets the value of the applicationHeader property.
     * 
     * @return
     *     possible object is
     *     {@link ApplicationHeaderType }
     *     
     */
    public ApplicationHeaderType getApplicationHeader() {
        return applicationHeader;
    }

    /**
     * Sets the value of the applicationHeader property.
     * 
     * @param value
     *     allowed object is
     *     {@link ApplicationHeaderType }
     *     
     */
    public void setApplicationHeader(ApplicationHeaderType value) {
        this.applicationHeader = value;
    }

    /**
     * Gets the value of the windowsRegistryKeysModified property.
     * 
     * @return
     *     possible object is
     *     {@link WindowsRegistryKeysModified }
     *     
     */
    public WindowsRegistryKeysModified getWindowsRegistryKeysModified() {
        return windowsRegistryKeysModified;
    }

    /**
     * Sets the value of the windowsRegistryKeysModified property.
     * 
     * @param value
     *     allowed object is
     *     {@link WindowsRegistryKeysModified }
     *     
     */
    public void setWindowsRegistryKeysModified(WindowsRegistryKeysModified value) {
        this.windowsRegistryKeysModified = value;
    }

    /**
     * Gets the value of the fileData property.
     * 
     * @return
     *     possible object is
     *     {@link FileData }
     *     
     */
    public FileData getFileData() {
        return fileData;
    }

    /**
     * Sets the value of the fileData property.
     * 
     * @param value
     *     allowed object is
     *     {@link FileData }
     *     
     */
    public void setFileData(FileData value) {
        this.fileData = value;
    }

    /**
     * Gets the value of the certificateData property.
     * 
     * @return
     *     possible object is
     *     {@link CertificateData }
     *     
     */
    public CertificateData getCertificateData() {
        return certificateData;
    }

    /**
     * Sets the value of the certificateData property.
     * 
     * @param value
     *     allowed object is
     *     {@link CertificateData }
     *     
     */
    public void setCertificateData(CertificateData value) {
        this.certificateData = value;
    }

    /**
     * Gets the value of the registryHandle property.
     * 
     * @return
     *     possible object is
     *     {@link RegistryHandle }
     *     
     */
    public RegistryHandle getRegistryHandle() {
        return registryHandle;
    }

    /**
     * Sets the value of the registryHandle property.
     * 
     * @param value
     *     allowed object is
     *     {@link RegistryHandle }
     *     
     */
    public void setRegistryHandle(RegistryHandle value) {
        this.registryHandle = value;
    }

    /**
     * Gets the value of the recordData property.
     * 
     * @return
     *     possible object is
     *     {@link RecordData }
     *     
     */
    public RecordData getRecordData() {
        return recordData;
    }

    /**
     * Sets the value of the recordData property.
     * 
     * @param value
     *     allowed object is
     *     {@link RecordData }
     *     
     */
    public void setRecordData(RecordData value) {
        this.recordData = value;
    }

    /**
     * Gets the value of the eventData property.
     * 
     * @return
     *     possible object is
     *     {@link EventData }
     *     
     */
    public EventData getEventData() {
        return eventData;
    }

    /**
     * Sets the value of the eventData property.
     * 
     * @param value
     *     allowed object is
     *     {@link EventData }
     *     
     */
    public void setEventData(EventData value) {
        this.eventData = value;
    }

    /**
     * Gets the value of the incident property.
     * 
     * @return
     *     possible object is
     *     {@link Incident }
     *     
     */
    public Incident getIncident() {
        return incident;
    }

    /**
     * Sets the value of the incident property.
     * 
     * @param value
     *     allowed object is
     *     {@link Incident }
     *     
     */
    public void setIncident(Incident value) {
        this.incident = value;
    }

    /**
     * Gets the value of the expectation property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the expectation property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getExpectation().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Expectation }
     * 
     * 
     */
    public List<Expectation> getExpectation() {
        if (expectation == null) {
            expectation = new ArrayList<Expectation>();
        }
        return this.expectation;
    }

    /**
     * Gets the value of the reference property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the reference property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getReference().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Reference }
     * 
     * 
     */
    public List<Reference> getReference() {
        if (reference == null) {
            reference = new ArrayList<Reference>();
        }
        return this.reference;
    }

    /**
     * Gets the value of the assessment property.
     * 
     * @return
     *     possible object is
     *     {@link Assessment }
     *     
     */
    public Assessment getAssessment() {
        return assessment;
    }

    /**
     * Sets the value of the assessment property.
     * 
     * @param value
     *     allowed object is
     *     {@link Assessment }
     *     
     */
    public void setAssessment(Assessment value) {
        this.assessment = value;
    }

    /**
     * Gets the value of the historyItem property.
     * 
     * @return
     *     possible object is
     *     {@link HistoryItem }
     *     
     */
    public HistoryItem getHistoryItem() {
        return historyItem;
    }

    /**
     * Sets the value of the historyItem property.
     * 
     * @param value
     *     allowed object is
     *     {@link HistoryItem }
     *     
     */
    public void setHistoryItem(HistoryItem value) {
        this.historyItem = value;
    }

    /**
     * Gets the value of the bulkObservable property.
     * 
     * @return
     *     possible object is
     *     {@link BulkObservable }
     *     
     */
    public BulkObservable getBulkObservable() {
        return bulkObservable;
    }

    /**
     * Sets the value of the bulkObservable property.
     * 
     * @param value
     *     allowed object is
     *     {@link BulkObservable }
     *     
     */
    public void setBulkObservable(BulkObservable value) {
        this.bulkObservable = value;
    }

    /**
     * Gets the value of the additionalData property.
     * 
     * @return
     *     possible object is
     *     {@link ExtensionType }
     *     
     */
    public ExtensionType getAdditionalData() {
        return additionalData;
    }

    /**
     * Sets the value of the additionalData property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExtensionType }
     *     
     */
    public void setAdditionalData(ExtensionType value) {
        this.additionalData = value;
    }

    /**
     * Gets the value of the restriction property.
     * 
     * @return
     *     possible object is
     *     {@link RestrictionType }
     *     
     */
    public RestrictionType getRestriction() {
        return restriction;
    }

    /**
     * Sets the value of the restriction property.
     * 
     * @param value
     *     allowed object is
     *     {@link RestrictionType }
     *     
     */
    public void setRestriction(RestrictionType value) {
        this.restriction = value;
    }

    /**
     * Gets the value of the extRestriction property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExtRestriction() {
        return extRestriction;
    }

    /**
     * Sets the value of the extRestriction property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExtRestriction(String value) {
        this.extRestriction = value;
    }

}
