//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.23 at 09:39:40 PM JST 
//


package ietf.params.xml.ns.iodef_2;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;simpleContent&gt;
 *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
 *       &lt;attribute name="type" use="required" type="{urn:ietf:params:xml:ns:iodef-2.0}recordpattern-type-type" /&gt;
 *       &lt;attribute name="ext-type" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="offset" type="{http://www.w3.org/2001/XMLSchema}integer" /&gt;
 *       &lt;attribute name="offsetunit" type="{urn:ietf:params:xml:ns:iodef-2.0}recordpattern-offsetunit-type" default="line" /&gt;
 *       &lt;attribute name="ext-offsetunit" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="instance" type="{http://www.w3.org/2001/XMLSchema}integer" /&gt;
 *     &lt;/extension&gt;
 *   &lt;/simpleContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "value"
})
@XmlRootElement(name = "RecordPattern")
public class RecordPattern {

    @XmlValue
    protected String value;
    @XmlAttribute(name = "type", required = true)
    protected RecordpatternTypeType type;
    @XmlAttribute(name = "ext-type")
    protected String extType;
    @XmlAttribute(name = "offset")
    protected BigInteger offset;
    @XmlAttribute(name = "offsetunit")
    protected RecordpatternOffsetunitType offsetunit;
    @XmlAttribute(name = "ext-offsetunit")
    protected String extOffsetunit;
    @XmlAttribute(name = "instance")
    protected BigInteger instance;

    /**
     * Gets the value of the value property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValue(String value) {
        this.value = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link RecordpatternTypeType }
     *     
     */
    public RecordpatternTypeType getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link RecordpatternTypeType }
     *     
     */
    public void setType(RecordpatternTypeType value) {
        this.type = value;
    }

    /**
     * Gets the value of the extType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExtType() {
        return extType;
    }

    /**
     * Sets the value of the extType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExtType(String value) {
        this.extType = value;
    }

    /**
     * Gets the value of the offset property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getOffset() {
        return offset;
    }

    /**
     * Sets the value of the offset property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setOffset(BigInteger value) {
        this.offset = value;
    }

    /**
     * Gets the value of the offsetunit property.
     * 
     * @return
     *     possible object is
     *     {@link RecordpatternOffsetunitType }
     *     
     */
    public RecordpatternOffsetunitType getOffsetunit() {
        if (offsetunit == null) {
            return RecordpatternOffsetunitType.LINE;
        } else {
            return offsetunit;
        }
    }

    /**
     * Sets the value of the offsetunit property.
     * 
     * @param value
     *     allowed object is
     *     {@link RecordpatternOffsetunitType }
     *     
     */
    public void setOffsetunit(RecordpatternOffsetunitType value) {
        this.offsetunit = value;
    }

    /**
     * Gets the value of the extOffsetunit property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExtOffsetunit() {
        return extOffsetunit;
    }

    /**
     * Sets the value of the extOffsetunit property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExtOffsetunit(String value) {
        this.extOffsetunit = value;
    }

    /**
     * Gets the value of the instance property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getInstance() {
        return instance;
    }

    /**
     * Sets the value of the instance property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setInstance(BigInteger value) {
        this.instance = value;
    }

}
