//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.23 at 09:39:40 PM JST 
//


package ietf.params.xml.ns.iodef_2;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for softwarereference-spec-name-type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="softwarereference-spec-name-type"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN"&gt;
 *     &lt;enumeration value="custom"/&gt;
 *     &lt;enumeration value="cpe"/&gt;
 *     &lt;enumeration value="swid"/&gt;
 *     &lt;enumeration value="ext-value"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "softwarereference-spec-name-type")
@XmlEnum
public enum SoftwarereferenceSpecNameType {

    @XmlEnumValue("custom")
    CUSTOM("custom"),
    @XmlEnumValue("cpe")
    CPE("cpe"),
    @XmlEnumValue("swid")
    SWID("swid"),
    @XmlEnumValue("ext-value")
    EXT_VALUE("ext-value");
    private final String value;

    SoftwarereferenceSpecNameType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static SoftwarereferenceSpecNameType fromValue(String v) {
        for (SoftwarereferenceSpecNameType c: SoftwarereferenceSpecNameType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
