//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.23 at 09:39:40 PM JST 
//


package ietf.params.xml.ns.iodef_2;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for systemimpact-type-type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="systemimpact-type-type"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN"&gt;
 *     &lt;enumeration value="admin"/&gt;
 *     &lt;enumeration value="takeover-account"/&gt;
 *     &lt;enumeration value="takeover-service"/&gt;
 *     &lt;enumeration value="takeover-system"/&gt;
 *     &lt;enumeration value="cps-manipulation"/&gt;
 *     &lt;enumeration value="cps-damage"/&gt;
 *     &lt;enumeration value="availability-data"/&gt;
 *     &lt;enumeration value="availibility-account"/&gt;
 *     &lt;enumeration value="availibility-service"/&gt;
 *     &lt;enumeration value="availibility-system"/&gt;
 *     &lt;enumeration value="damaged-system"/&gt;
 *     &lt;enumeration value="damaged-data"/&gt;
 *     &lt;enumeration value="breach-proprietary"/&gt;
 *     &lt;enumeration value="breach-privacy"/&gt;
 *     &lt;enumeration value="breach-credential"/&gt;
 *     &lt;enumeration value="breach-configuration"/&gt;
 *     &lt;enumeration value="integrity-data"/&gt;
 *     &lt;enumeration value="integrity-configuration"/&gt;
 *     &lt;enumeration value="integrity-hardware"/&gt;
 *     &lt;enumeration value="traffic-redirection"/&gt;
 *     &lt;enumeration value="monitoring-traffic"/&gt;
 *     &lt;enumeration value="monitoring-host"/&gt;
 *     &lt;enumeration value="policy"/&gt;
 *     &lt;enumeration value="ext-value"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "systemimpact-type-type")
@XmlEnum
public enum SystemimpactTypeType {

    @XmlEnumValue("admin")
    ADMIN("admin"),
    @XmlEnumValue("takeover-account")
    TAKEOVER_ACCOUNT("takeover-account"),
    @XmlEnumValue("takeover-service")
    TAKEOVER_SERVICE("takeover-service"),
    @XmlEnumValue("takeover-system")
    TAKEOVER_SYSTEM("takeover-system"),
    @XmlEnumValue("cps-manipulation")
    CPS_MANIPULATION("cps-manipulation"),
    @XmlEnumValue("cps-damage")
    CPS_DAMAGE("cps-damage"),
    @XmlEnumValue("availability-data")
    AVAILABILITY_DATA("availability-data"),
    @XmlEnumValue("availibility-account")
    AVAILIBILITY_ACCOUNT("availibility-account"),
    @XmlEnumValue("availibility-service")
    AVAILIBILITY_SERVICE("availibility-service"),
    @XmlEnumValue("availibility-system")
    AVAILIBILITY_SYSTEM("availibility-system"),
    @XmlEnumValue("damaged-system")
    DAMAGED_SYSTEM("damaged-system"),
    @XmlEnumValue("damaged-data")
    DAMAGED_DATA("damaged-data"),
    @XmlEnumValue("breach-proprietary")
    BREACH_PROPRIETARY("breach-proprietary"),
    @XmlEnumValue("breach-privacy")
    BREACH_PRIVACY("breach-privacy"),
    @XmlEnumValue("breach-credential")
    BREACH_CREDENTIAL("breach-credential"),
    @XmlEnumValue("breach-configuration")
    BREACH_CONFIGURATION("breach-configuration"),
    @XmlEnumValue("integrity-data")
    INTEGRITY_DATA("integrity-data"),
    @XmlEnumValue("integrity-configuration")
    INTEGRITY_CONFIGURATION("integrity-configuration"),
    @XmlEnumValue("integrity-hardware")
    INTEGRITY_HARDWARE("integrity-hardware"),
    @XmlEnumValue("traffic-redirection")
    TRAFFIC_REDIRECTION("traffic-redirection"),
    @XmlEnumValue("monitoring-traffic")
    MONITORING_TRAFFIC("monitoring-traffic"),
    @XmlEnumValue("monitoring-host")
    MONITORING_HOST("monitoring-host"),
    @XmlEnumValue("policy")
    POLICY("policy"),
    @XmlEnumValue("ext-value")
    EXT_VALUE("ext-value");
    private final String value;

    SystemimpactTypeType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static SystemimpactTypeType fromValue(String v) {
        for (SystemimpactTypeType c: SystemimpactTypeType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
