//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.02.13 at 04:28:03 PM JST 
//


package ietf.params.xml.ns.iodef_1;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded" minOccurs="0">
 *         &lt;element ref="{urn:ietf:params:xml:ns:iodef-1.0}IncidentID"/>
 *         &lt;element ref="{urn:ietf:params:xml:ns:iodef-1.0}Description"/>
 *         &lt;element ref="{urn:ietf:params:xml:ns:iodef-1.0}IODEF_Document"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "incidentIDOrDescriptionOrIODEFDocument"
})
@XmlRootElement(name = "NewDataSet")
public class NewDataSet {

    @XmlElements({
        @XmlElement(name = "IncidentID", type = IncidentID.class, nillable = true),
        @XmlElement(name = "Description", type = Description.class, nillable = true),
        @XmlElement(name = "IODEF_Document", type = IODEFDocument.class)
    })
    protected List<Object> incidentIDOrDescriptionOrIODEFDocument;

    /**
     * Gets the value of the incidentIDOrDescriptionOrIODEFDocument property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the incidentIDOrDescriptionOrIODEFDocument property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getIncidentIDOrDescriptionOrIODEFDocument().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link IncidentID }
     * {@link Description }
     * {@link IODEFDocument }
     * 
     * 
     */
    public List<Object> getIncidentIDOrDescriptionOrIODEFDocument() {
        if (incidentIDOrDescriptionOrIODEFDocument == null) {
            incidentIDOrDescriptionOrIODEFDocument = new ArrayList<Object>();
        }
        return this.incidentIDOrDescriptionOrIODEFDocument;
    }

}
